#!/bin/sh
set -e

PLATFORM=$1
ROOT_DIR=`pwd`
MAIN_WORKING_DIR=$ROOT_DIR/stytch-multiplatform
SHARED_WORKING_DIR=$ROOT_DIR/stytch-multiplatform-shared

buildAndPublishSharedSdkFirst() {
    cd $SHARED_WORKING_DIR
    echo "Building shared stuff first..."
    
    echo "Building iOS library..."
    cd sdk/shared/src/iosMain/interop

    # clear out any old stuff
    rm -rf iOS.xcarchive libStytch* Simulator.xcarchive StytchShared

    # create header file (for cinterop generation)
    sudo swiftc -emit-objc-header Sources/StytchShared/StytchShared.swift

    # build xcarchives for platforms
    xcodebuild archive -scheme StytchShared -configuration Release -destination 'generic/platform=iOS' -archivePath "./iOS" SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES &&
    xcodebuild archive -scheme StytchShared -configuration Release -destination 'generic/platform=iOS Simulator' -archivePath "./Simulator" SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES

    # convert the objects into libraries
    ar -crs libStytchIos.a ./iOS.xcarchive/Products/Users/jhaven/Objects/StytchShared.o && 
    ar -crs libStytchSimulator.a ./Simulator.xcarchive/Products/Users/jhaven/Objects/StytchShared.o

    cd $SHARED_WORKING_DIR
    ./gradlew :sdk:shared:publishToMavenLocal
}

buildAndCopyAndroid() {
    cd $MAIN_WORKING_DIR
    echo "Building android artifact..."
    ./gradlew :sdk:consumer-headless:publishToMavenLocal :sdk:consumer-extensions:publishToMavenLocal
}

buildAndCopyIos() {
    cd $MAIN_WORKING_DIR
    echo "Building iOS artifact..."
    ./gradlew assembleStytchConsumerSDKXCFramework assembleStytchConsumerExtensionsSDKXCFramework
    cp -r sdk/consumer-headless/build/XCFrameworks/release/StytchConsumerSDK.xcframework $ROOT_DIR/stytch-ios
    cp -r sdk/consumer-headless/build/XCFrameworks/release/StytchConsumerSDK.xcframework $ROOT_DIR/react-native/consumer/ios
}

buildAndCopyRn() {
    cd $MAIN_WORKING_DIR
    echo "Building RN artifacts..."
    ./gradlew kotlinUpgradeYarnLock :sdk:consumer-headless:jsBrowserProductionLibraryDistribution
    cp -r sdk/consumer-headless/build/dist/js/productionLibrary/ $ROOT_DIR/react-native/consumer/lib
    cd $ROOT_DIR/react-native/consumer
    yarn build
    updateRnDemoApp
}

updateRnDemoApp() {
    cd $ROOT_DIR/examples/rn
    yarn remove @stytch/react-native-consumer
    yarn add file:$ROOT_DIR/react-native/consumer
}

main() {
    buildAndPublishSharedSdkFirst
    if [ -z "$PLATFORM" ]; then
        echo "Building for all platforms"
        buildAndCopyAndroid
        buildAndCopyIos
        buildAndCopyRn
    elif [[ "$PLATFORM" == "android" ]]; then
        buildAndCopyAndroid
    elif [[ "$PLATFORM" == "ios" ]]; then
        buildAndCopyIos
    elif [[ "$PLATFORM" == "rn" ]]; then
        buildAndCopyRn
    fi
    cd $ROOT_DIR
    echo "Done."
}

main