#!/bin/sh
set -e

PLATFORM=$1
ROOT_DIR=`pwd`
MAIN_WORKING_DIR=$ROOT_DIR/stytch-multiplatform
SHARED_WORKING_DIR=$ROOT_DIR/stytch-multiplatform-shared

buildAndPublishSwiftUtils() {
    cd StytchSwiftUtils
    # clear out any old stuff
    rm -rf derived archives StytchSwiftUtils.xcframework StytchSwiftUtils-Swift.h
    
    # build (to get the header file)
    xcodebuild -project StytchSwiftUtils.xcodeproj -scheme StytchSwiftUtils -configuration Release -destination 'generic/platform=iOS' -derivedDataPath ./derived IPHONEOS_DEPLOYMENT_TARGET=15.0 SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES ONLY_ACTIVE_ARCH=NO build
    xcodebuild -project StytchSwiftUtils.xcodeproj -scheme StytchSwiftUtils -configuration Release -destination 'generic/platform=iOS Simulator' -derivedDataPath ./derived IPHONEOS_DEPLOYMENT_TARGET=15.0 SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES ONLY_ACTIVE_ARCH=NO build
    
    # archive project
    xcodebuild -project StytchSwiftUtils.xcodeproj -scheme StytchSwiftUtils -configuration Release -archivePath "./archives/iOS" -destination 'generic/platform=iOS' -derivedDataPath ./derived IPHONEOS_DEPLOYMENT_TARGET=15.0 SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES ONLY_ACTIVE_ARCH=NO archive
    xcodebuild -project StytchSwiftUtils.xcodeproj -scheme StytchSwiftUtils -configuration Release -archivePath "./archives/Simulator" -destination 'generic/platform=iOS Simulator' -derivedDataPath ./derived IPHONEOS_DEPLOYMENT_TARGET=15.0 SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES ONLY_ACTIVE_ARCH=NO archive
    
    # create xcframework
    xcodebuild -create-xcframework \
        -framework archives/iOS.xcarchive/Products/Library/Frameworks/StytchSwiftUtils.framework \
        -framework archives/Simulator.xcarchive/Products/Library/Frameworks/StytchSwiftUtils.framework \
        -output StytchSwiftUtils.xcframework

    # copy header file to usable location (for cinterop generation)
    cp ./derived/Build/Intermediates.noindex/StytchSwiftUtils.build/Release-iphoneos/StytchSwiftUtils.build/DerivedSources/StytchSwiftUtils-Swift.h ../stytch-multiplatform-shared/sdk/shared/src/iosMain/interop/StytchSwiftUtils-device.h
    cp ./derived/Build/Intermediates.noindex/StytchSwiftUtils.build/Release-iphonesimulator/StytchSwiftUtils.build/DerivedSources/StytchSwiftUtils-Swift.h ../stytch-multiplatform-shared/sdk/shared/src/iosMain/interop/StytchSwiftUtils-simulator.h

    # copy xcframework to usable locations
    cp -r ./StytchSwiftUtils.xcframework ../stytch-multiplatform-shared/sdk/shared/src/iosMain/interop/
    cp -r ./StytchSwiftUtils.xcframework ../stytch-ios
}

buildAndPublishSharedSdkFirst() {
    echo "Building shared stuff first..."
    buildAndPublishSwiftUtils

    cd $SHARED_WORKING_DIR
    ./gradlew clean :sdk:shared:assembleStytchSharedSDKXCFramework :sdk:shared:publishToMavenLocal
    cp -r sdk/shared/build/XCFrameworks/release/StytchSharedSDK.xcframework $ROOT_DIR/stytch-ios
}

buildAndCopyAndroid() {
    cd $MAIN_WORKING_DIR
    echo "Building android artifact..."
    ./gradlew clean :sdk:consumer-headless:publishToMavenLocal --rerun-tasks
}

buildAndCopyIos() {
    echo "Building iOS artifacts..."
    cd $MAIN_WORKING_DIR
    ./gradlew clean assembleStytchConsumerSDKXCFramework --rerun-tasks
    cp -r sdk/consumer-headless/build/XCFrameworks/release/StytchConsumerSDK.xcframework $ROOT_DIR/stytch-ios
}

buildAndCopyRn() {
    cd $MAIN_WORKING_DIR
    echo "Building RN artifacts..."
    ./gradlew clean kotlinUpgradeYarnLock :sdk:consumer-headless:assemble :sdk:consumer-headless:jsBrowserProductionLibraryDistribution --rerun-tasks
    mkdir -p $ROOT_DIR/react-native/consumer/lib
    cp -r sdk/consumer-headless/build/dist/js/productionLibrary/consumer-headless* $ROOT_DIR/react-native/consumer/lib
    cd $ROOT_DIR/react-native/consumer
    yarn build
    updateRnDemoApp
}

updateRnDemoApp() {
    cd $ROOT_DIR/examples/rn
    yarn remove @stytch/react-native-consumer
    yarn add file:$ROOT_DIR/react-native/consumer
}

main() {
    buildAndPublishSharedSdkFirst
    if [ -z "$PLATFORM" ]; then
        echo "Building for all platforms"
        buildAndCopyAndroid
        buildAndCopyIos
        buildAndCopyRn
    elif [[ "$PLATFORM" == "shared" ]]; then
        echo "Already built"
    elif [[ "$PLATFORM" == "android" ]]; then
        buildAndCopyAndroid
    elif [[ "$PLATFORM" == "ios" ]]; then
        buildAndCopyIos
    elif [[ "$PLATFORM" == "rn" ]]; then
        buildAndCopyRn
    fi
    cd $ROOT_DIR
    echo "Done."
}

main