package com.stytch.sdk.consumer.dfp

import com.stytch.sdk.StytchApi
import com.stytch.sdk.data.StytchDispatchers
import com.stytch.sdk.data.StytchError
import com.stytch.sdk.dfp.DFPNotConfiguredError
import com.stytch.sdk.dfp.DFPProvider
import kotlinx.coroutines.withContext
import kotlin.coroutines.cancellation.CancellationException
import kotlin.js.JsExport

/** Device fingerprinting (DFP) integration. Provides a telemetry ID for Stytch's fraud prevention layer. */
@StytchApi
@JsExport
public interface DFPClient {
    /**
     * Returns a DFP telemetry ID generated by the Stytch device fingerprinting SDK. This is a local
     * operation — it does not make a network call to the Stytch API. Pass the returned ID to your
     * backend, which can use it in server-side Stytch DFP lookup calls.
     *
     * **Kotlin:**
     * ```kotlin
     * StytchConsumer.dfp.getTelemetryId()
     * ```
     *
     * **iOS:**
     * ```swift
     * let telemetryId = try await StytchConsumer.dfp.getTelemetryId()
     * ```
     *
     * **React Native:**
     * ```js
     * StytchConsumer.dfp.getTelemetryId()
     * ```
     *
     * @return The DFP telemetry ID string to pass to your backend.
     *
     * @throws [com.stytch.sdk.dfp.DFPNotConfiguredError] if DFP was not configured during SDK initialization.
     * @throws [CancellationException] if the coroutine is cancelled.
     */
    @Throws(StytchError::class, CancellationException::class)
    public suspend fun getTelemetryId(): String
}

internal class DFPClientImpl(
    private val dispatchers: StytchDispatchers,
    private val dfpProvider: DFPProvider?,
) : DFPClient {
    @Throws(StytchError::class, CancellationException::class)
    override suspend fun getTelemetryId(): String =
        withContext(dispatchers.ioDispatcher) {
            dfpProvider?.getTelemetryId() ?: throw DFPNotConfiguredError()
        }
}
