package com.stytch.sdk.utils

import com.google.devtools.ksp.getDeclaredFunctions
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.PlatformInfo
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import com.google.devtools.ksp.symbol.Modifier
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.LambdaTypeName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.UNIT
import com.squareup.kotlinpoet.ksp.toTypeName
import com.squareup.kotlinpoet.ksp.writeTo
import java.io.File

private val COROUTINE_SCOPE = ClassName("kotlinx.coroutines", "CoroutineScope")
private val DISPATCHERS = ClassName("kotlinx.coroutines", "Dispatchers")
private val JOB = ClassName("kotlinx.coroutines", "Job")
private val THROWABLE_CN = ClassName("kotlin", "Throwable")

class StytchCallbackProcessor(
    private val logger: KSPLogger,
    private val options: Map<String, String>,
    platforms: List<PlatformInfo>,
) : SymbolProcessor {
    // Only run in the commonMain compilation (platforms.size > 1), same guard as StytchDtoProcessor.
    private val isCommonMain = platforms.size > 1

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (!isCommonMain) return emptyList()

        val outputDirPath =
            options["stytchCallbackOutputDir"] ?: run {
                logger.warn("stytchCallbackOutputDir not set, skipping callback generation")
                return emptyList()
            }
        val outputDir = File(outputDirPath).also { it.mkdirs() }

        // Symbols whose parameter/return types are not yet resolved (generated by another KSP
        // processor in this same round) are deferred and retried in the next round, by which
        // point all generated types are available.
        val deferred = mutableListOf<KSAnnotated>()

        resolver
            .getSymbolsWithAnnotation("com.stytch.sdk.StytchApi")
            .filterIsInstance<KSClassDeclaration>()
            .forEach { classDecl ->
                if (!tryGenerateCallbackFile(classDecl, outputDir)) {
                    deferred.add(classDecl)
                }
            }

        return deferred
    }

    // Returns false if any type is an error type (unresolvable this round — defer to next round).
    private fun tryGenerateCallbackFile(classDecl: KSClassDeclaration, outputDir: File): Boolean {
        val suspendFunctions =
            classDecl
                .getDeclaredFunctions()
                .filter { Modifier.SUSPEND in it.modifiers }
                .toList()

        if (suspendFunctions.isEmpty()) return true

        // Check all parameter and return types are fully resolved before generating.
        for (func in suspendFunctions) {
            if (func.returnType?.resolve()?.isError == true) return false
            if (func.parameters.any { it.type.resolve().isError }) return false
        }

        generateCallbackFile(classDecl, outputDir, suspendFunctions)
        return true
    }

    private fun generateCallbackFile(
        classDecl: KSClassDeclaration,
        outputDir: File,
        suspendFunctions: List<KSFunctionDeclaration>,
    ) {
        val packageName = classDecl.packageName.asString()
        val interfaceName = classDecl.simpleName.asString()

        val fileSpec =
            FileSpec
                .builder(packageName, "${interfaceName}Callbacks")
                .apply { suspendFunctions.forEach { addFunction(buildCallbackExtension(classDecl, it)) } }
                .build()

        fileSpec.writeTo(outputDir)
    }

    private fun buildCallbackExtension(
        classDecl: KSClassDeclaration,
        func: KSFunctionDeclaration,
    ): FunSpec {
        val packageName = classDecl.packageName.asString()
        val interfaceName = classDecl.simpleName.asString()
        val funcName = func.simpleName.asString()
        val returnType = func.returnType!!.toTypeName()

        val params =
            func.parameters.map { param ->
                ParameterSpec.builder(param.name!!.asString(), param.type.toTypeName()).build()
            }
        val callArgs = params.joinToString(", ") { it.name }

        val onSuccessType =
            LambdaTypeName.get(
                parameters = listOf(ParameterSpec.builder("value", returnType).build()),
                returnType = UNIT,
            )
        val onFailureType =
            LambdaTypeName.get(
                parameters = listOf(ParameterSpec.builder("error", THROWABLE_CN).build()),
                returnType = UNIT,
            )

        val body =
            CodeBlock
                .builder()
                .beginControlFlow("return %T(%T.Default).launch", COROUTINE_SCOPE, DISPATCHERS)
                .beginControlFlow("try")
                .addStatement("onSuccess(%N($callArgs))", funcName)
                .nextControlFlow("catch (t: %T)", THROWABLE_CN)
                .addStatement("onFailure(t)")
                .endControlFlow()
                .endControlFlow()
                .build()

        return FunSpec
            .builder(funcName)
            .addModifiers(KModifier.PUBLIC)
            .receiver(ClassName(packageName, interfaceName))
            .addParameters(params)
            .addParameter("onSuccess", onSuccessType)
            .addParameter("onFailure", onFailureType)
            .returns(JOB)
            .addCode(body)
            .build()
    }
}

class StytchCallbackProcessorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        StytchCallbackProcessor(environment.logger, environment.options, environment.platforms)
}
