package com.stytch.sdk.utils

import com.google.devtools.ksp.getDeclaredFunctions
import com.google.devtools.ksp.getDeclaredProperties
import com.google.devtools.ksp.processing.KSPLogger
import com.google.devtools.ksp.processing.PlatformInfo
import com.google.devtools.ksp.processing.Resolver
import com.google.devtools.ksp.processing.SymbolProcessor
import com.google.devtools.ksp.processing.SymbolProcessorEnvironment
import com.google.devtools.ksp.processing.SymbolProcessorProvider
import com.google.devtools.ksp.symbol.KSAnnotated
import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.google.devtools.ksp.symbol.KSDeclaration
import com.google.devtools.ksp.symbol.KSFunctionDeclaration
import java.io.File

/**
 * KSP processor that extracts KDoc comments from @JsExport-annotated declarations and writes
 * them to a JSON file for use by InjectJsDocTask during the JS build.
 *
 * Output format: { "TypeName": "doc", "TypeName.memberName": "doc", ... }
 */
class StytchJsDocExtractor(
    private val logger: KSPLogger,
    private val options: Map<String, String>,
    platforms: List<PlatformInfo>,
) : SymbolProcessor {
    // Only run in the commonMain compilation (platforms.size > 1).
    private val isCommonMain = platforms.size > 1
    private val docs = mutableMapOf<String, String>()
    private var finished = false

    override fun process(resolver: Resolver): List<KSAnnotated> {
        if (!isCommonMain) return emptyList()

        resolver
            .getSymbolsWithAnnotation("kotlin.js.JsExport")
            .forEach { symbol ->
                when (symbol) {
                    is KSClassDeclaration -> collectClass(symbol)
                    is KSFunctionDeclaration -> collectTopLevelFunction(symbol)
                    else -> Unit
                }
            }

        return emptyList()
    }

    override fun finish() {
        if (!isCommonMain || finished) return
        finished = true

        val outputDirPath =
            options["stytchJsDocOutputDir"] ?: run {
                logger.warn("stytchJsDocOutputDir not set, skipping JsDoc extraction")
                return
            }

        val outputFile = File(outputDirPath, "jsdoc-map.txt").also { it.parentFile.mkdirs() }
        outputFile.writeText(buildDocMap(docs))
        logger.info("StytchJsDocExtractor: wrote ${docs.size} entries to ${outputFile.absolutePath}")
    }

    private fun collectClass(cls: KSClassDeclaration) {
        val name = cls.simpleName.asString()
        cls.docString?.let { docs[name] = cleanDoc(it) }

        // Direct members
        cls.getDeclaredFunctions().forEach { fn ->
            val fnName = fn.simpleName.asString()
            if (fnName !in SYNTHETIC_MEMBERS) {
                fn.docString?.let { docs["$name.$fnName"] = cleanDoc(it) }
            }
        }
        cls.getDeclaredProperties().forEach { prop ->
            val propName = prop.simpleName.asString()
            prop.docString?.let { docs["$name.$propName"] = cleanDoc(it) }
        }

        // Nested classes (e.g. sealed class subclasses)
        cls.declarations.filterIsInstance<KSClassDeclaration>().forEach { nested ->
            val nestedName = nested.simpleName.asString()
            nested.docString?.let {
                val doc = cleanDoc(it)
                // Store under both "Outer.Inner" (for namespace-block matching)
                // and "Inner" (fallback key used when outer context isn't tracked)
                docs["$name.$nestedName"] = doc
                docs.putIfAbsent(nestedName, doc)
            }

            // Members of nested class (e.g. constructor val params become getters in TS)
            nested.getDeclaredFunctions().forEach { fn ->
                val fnName = fn.simpleName.asString()
                if (fnName !in SYNTHETIC_MEMBERS) {
                    fn.docString?.let { docs["$nestedName.$fnName"] = cleanDoc(it) }
                }
            }
            nested.getDeclaredProperties().forEach { prop ->
                val propName = prop.simpleName.asString()
                prop.docString?.let { docs["$nestedName.$propName"] = cleanDoc(it) }
            }
        }
    }

    private fun collectTopLevelFunction(fn: KSFunctionDeclaration) {
        fn.docString?.let { docs[fn.simpleName.asString()] = cleanDoc(it) }
    }
}

/** Strip KDoc markers and normalize whitespace. KSP may or may not include them. */
private fun cleanDoc(raw: String): String =
    raw
        .trim()
        .removePrefix("/**")
        .removeSuffix("*/")
        .lines()
        .joinToString("\n") { it.trim().removePrefix("*").trim() }
        .trim()

/** Members generated by the Kotlin compiler that we never want to document. */
private val SYNTHETIC_MEMBERS =
    setOf("<init>", "equals", "hashCode", "toString", "copy", "compareTo", "component1",
        "component2", "component3", "component4", "component5")

// Format: one entry per line — "Key\tValue" (tab-separated, newlines in value escaped as \n)
private fun buildDocMap(map: Map<String, String>): String =
    map.entries.joinToString("\n") { (k, v) ->
        "$k\t${v.replace("\n", "\\n")}"
    }

class StytchJsDocExtractorProvider : SymbolProcessorProvider {
    override fun create(environment: SymbolProcessorEnvironment): SymbolProcessor =
        StytchJsDocExtractor(environment.logger, environment.options, environment.platforms)
}
