name: Quality Control

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-shared:
    name: Lint & Test (stytch-multiplatform-shared)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Write local.properties (for local CI)
        if: ${{ env.ACT }}
        run: echo "sdk.dir=$ANDROID_HOME" > stytch-multiplatform-shared/local.properties 

      - name: Lint
        working-directory: stytch-multiplatform-shared
        run: ./gradlew ktlintCheck

      - name: Test
        working-directory: stytch-multiplatform-shared
        run: ./gradlew jvmTest

  check-consumer:
    name: Lint & Test (stytch-multiplatform)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Write local.properties (for local CI)
        if: ${{ env.ACT }}
        run: |
          echo "sdk.dir=$ANDROID_HOME" > stytch-multiplatform-shared/local.properties
          echo "sdk.dir=$ANDROID_HOME" > stytch-multiplatform/local.properties

      - name: Publish shared to mavenLocal
        working-directory: stytch-multiplatform-shared
        run: ./gradlew publishKotlinMultiplatformPublicationToMavenLocal publishJvmPublicationToMavenLocal

      - name: Lint
        working-directory: stytch-multiplatform
        run: ./gradlew ktlintCheck

      - name: Test
        working-directory: stytch-multiplatform
        run: ./gradlew jvmTest
